# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    application:
        name: ssdc-admin
    activiti:
        asyncExecutorEnabled: false
        asyncExecutorActivate: false
    profiles:
         active: dev,swagger
    jackson:
        serialization.write_dates_as_timestamps: false   
    mvc:
        favicon:
            enabled: false      
                  
management:
    endpoints:
        web:
            exposure:
                include: "info,health,prometheus"

ctsi:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    #cors:
        #allowed-origins: "*"
        #allowed-methods: "*"
        #allowed-headers: "*"
        #exposed-headers: "Authorization,Link,X-Total-Count"
        #allow-credentials: true
        #max-age: 1800
    swagger:
        default-include-pattern: /api/.*
        title: ctsi API
        description: ctsi API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:
    systemconfig:
        webfiles: /Users/bodhi/allSelf/server/webfiles

    jwtfilter:
        enable: false

    userService: userServiceImpl
    sqlService: sqlServiceImpl
    metaDataService: metaDataServiceImpl
    menuService: menuServiceImpl
    bigDataService: 
